#!/bin/sh

# This is a modified version of the NXT install script by j0b for Synology NAS. 
# Original located here: https://github.com/jobbet/nxt

# This has been tested on a DS213j.

# Send me some NXT coins if you find this useful. 
# NXT: 5382956979630465590

# dmmh

# NXT-Client configuration
source "/etc/nxt/nxt.conf"
log=$install_dir/nxt.log
tmp_log=$cfg_dir/nxtclient.log
wget_bin=$(which wget);
java_bin=$(which java);

check(){
	touch $tmp_log;
	if [[ -z "$pidfile" ]] || [[ -z "$nxtuser" ]] || [[ -z "$client_start_args" ]]; then
		echo "Missing configuration in nxt.conf";
		exit 0;
	fi
	if [[ -z "$java_bin" ]]; then
		echo "Java is not installed. Please install Java first. Easiest way is using Synology Java Manager, get it here: http://www.synology.com/en-uk/dsm/app_packages/JavaManager";
		exit 0;
	fi
}

start() {
	echo "Starting NXT client...";
	check;
	c=`pwd`;
	if [ -e $pidfile ] ; then
		echo "NXT client is already running. PID=`cat $pidfile`";
		exit 0;
	fi
	if [[ -e $log ]]; then
		rm $log
	fi
	touch $log;
	cd $install_dir;
	"$java_bin" $client_start_args >>$log 2>&1 & pid=$!;
	touch $pidfile && chown $nxtuser:$nxtuser $pidfile;
	echo $pid > $pidfile;
	cd $c;
	status;
	echo "It might take up to 5 minutes or so before you will be able to access the NXT client via your browser...be patient.";
	echo "You can watch the NXT client's output by using $ "$script_dir"/nxtclient.sh log";
	exit 1;
}

stop() {
	c=`pwd`
	echo "Trying to stop NXT-Client..."
	if [ -e $pidfile ] ; then
		pid=`cat $pidfile`
		kill $pid
		rm $pidfile		
		status
	else
		echo "NXT client is not running. No PID file."
	fi
}

status() {
	check
	touch $current_version
	version=`cat $current_version`
	client_version=$($wget_bin -q -O -  http://download.nxtcrypto.org | sed 's/\(>\|<\)/ /g' | awk {'print $3 '} | egrep -v "(e.zip|e.sha256|changelog.txt)" | egrep '(zip$)' | tail -n 1);
	if [[ "$version"] != '' ]] && [[ "$client_version"] != '' ]]; then
		if [[ "$version" != "$client_version" ]]; then 
			echo "A newer version of NXT client is available. Current version: $version, version available: $client_version".
			echo "Trying to update NXT client..."
			$cfg_dir/install.sh update
		fi
	fi
	if [ -e $pidfile ] ; then
		echo "NXT client is running!"
	else
		echo "NXT client stopped."
	fi
}

log() {
	cat $log
} 

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	status)
		status
	;;
	log)
		log
	;;
	check)
		check
	;;
	*)

	N=$script_dir/${0##*/}
	echo "Usage: $N {start|stop|status|log|check}" >&2
	exit 1
	;;
esac

exit 0

# ORIGINAL LICENSE:
#  ----------------------------------------------------------------------------
#  "THE NXT-WARE LICENSE" NXT: 13570469120032392161 (Revision: 25519)
#  j0b <gemeni@gmail.com> wrote this file. As long as you retain this notice you
#  can do whatever you want with this stuff. IF you think this stuff is worth it, 
#  you can send me NXT, my public key is above.
#  ----------------------------------------------------------------------------
